
py_library(
    name = "my_package_lib",
    srcs = ["//my_package:class_data.py",
            "//my_package:class_foo.py"],
    visibility = ["//my_application:__pkg__"]
    #visibility = ["//visibility:public"] # or make it completely public
)
